@startuml kelompok1
actor User
participant System
database DB
group user membuat budget
  User -> System : klik menu budget
  User <-- System : redirect ke menu budget
  User -> System : klik tombol create
  User <-- System : redirect ke halaman tambah budget
  User -> System : masukkan data (name, category, threshold amount, transaction type,start at, end at), klik save 
  System -> System : validate data
  alt data tidak lengkap
  User <-- System : tampilkan error validasi
  end
  System -> System : process data
  System -> DB : simpan data
  System <-- DB : data berhasil disimpan
  User <-- System : notifikasi data berhasil disimpan
end
@enduml