@startuml kelompok1
actor User
participant System
database DB
group user menghapus budget
  User -> System : klik menu budget
  System -> DB : dapatkan semua data budget
  System <-- DB : berhasil dapat semua data budget
  User <-- System : redirect ke menu budget, dan tampilkan data
  User -> System : klik hapus pada data yang ingin di dihapus
  System -> DB : menghapus data
  alt database error
  System <-- DB : error database
  User <-- System : tampilkan error database
  end
  System <-- DB : data berhasil dihapus
  User <-- System : notifikasi data berhasil dihapus
end
@enduml