@startuml kelompok1
actor "User / Admin" as User
participant System
database DB
group user mengubah password
  User -> System : masuk ke menu profile
  System -> DB : dapatkan data profile
  System <-- DB : berhasil dapat data
  System --> User : redirect ke menu profile,dan tampilkan data
  User -> System : masukkan masukkan curent, new password, dan confirm new password. klik tombol "save"
  System -> System : validate data
  alt password kurang dari 8 angka/haruf
  User <-- System : error validasi
  end
  alt new password yang di masukkan berbeda dengan confirm new password 
  User <-- System :error validasi
  end
  System -> System : process data
  System -> DB : update password
  System <-- DB : update password berhasil
  System --> User : notifikasi berhasil di ubah
end
@enduml