@startuml kelompok1
actor User
actor Admin
participant System
database DB
group Admin mengubah password user
  User -> Admin: mengirimkan email untuk merubah password
  Admin -> Admin : checking email
  Admin -> System: ke menu user
  System -> DB: dapatkan semua data user
  System <-- DB: berhasil dapatkan semua data user
  Admin -> System: pilih user
  Admin <-- System: redirect ke menu ubah password
  Admin -> System: masukkan new password, dan confirm new password user, klick "save"
  System -> System : validate data
  alt passwor yang di masukkan kurang dari 8 huruf/angka
    Admin <-- System : error validasi
  end
  alt new password berbeda dengan confirm new password
  Admin <-- System : error validasi
  end
  System -> DB : update data password
  System <-- DB : berhasil update password
  Admin <-- System : password berhasil di ubah
  Admin --> User : reply email ubah new password berhasil
  end
@enduml