@startuml kelompok1
actor User
participant System
database DB
group user mengubah kategori
  User -> System : klik menu category
  System -> DB : dapatkan semua data category
  System <-- DB : berhasil dapat semua data category
  User <-- System : redirect ke menu category, dan tampilkan data
  User -> System : klik edit pada data yang ingin di diubah
  System -> DB : dapatkan data category
  System <-- DB : berhasil dapat data category
  User <-- System : redirect ke halaman edit category, dan tampilkan data
  User -> System : masukkan data (nama), klik save 
  System -> System : validate data
  alt data tidak lengkap
  User <-- System : tampilkan error validasi
  end
  System -> System : process data
  System -> DB : simpan data
  System <-- DB : data berhasil disimpan
  User <-- System : notifikasi data berhasil disimpan
end
@enduml