@startuml deployment
node "Client Device" {
    [Browser]
}

node "Ubuntu" {
  node "Apache2" {
    [Apache2]
    node "Web Server (Laravel)" {
        [Laravel Application]
    }
  }

  node "Docker Container" {
    node "Database Server" {
        [PostgreSQL Database]
    }
}

}

[Browser] --> [Apache2]: HTTP/HTTPS
[Apache2] --> [Laravel Application]: HTTP
[Laravel Application] --> [PostgreSQL Database]: SQL Queries
@enduml
